# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


user1 = User.create!(firstname: "henry", lastname: "ryu", password: "henry123", email: "henry@gmail.com", zipcode: "94538", birthday: Date.new(1984, 1, 27))
user2 = User.create!(firstname: "billy", lastname: "jan", password: "billy123", email: "billy@gmail.com", zipcode: "94224", birthday: Date.new(1981, 12, 2))
user3 = User.create!(firstname: "joy", lastname: "su", password: "joy123", email: "joy@gmail.com", zipcode: "93538", birthday: Date.new(1974, 1, 3))
user4 = User.create!(firstname: "harry1", lastname: "kane", password: "harry1123", email: "harry1@gmail.com", zipcode: "94838", birthday: Date.new(1994, 4, 27))
user5 = User.create!(firstname: "pepper99", lastname: "spice", password: "pepper99123", email: "pepper99@gmail.com", zipcode: "94222", birthday: Date.new(1922, 5, 9))
user6 = User.create!(firstname: "alvin9", lastname: "lu", password: "alvin9123", email: "alvin9@gmail.com", zipcode: "94333", birthday: Date.new(1984, 11, 11))
user7 = User.create!(firstname: "ben99", lastname: "weil", password: "ben99123", email: "ben99@gmail.com", zipcode: "94555", birthday: Date.new(1924, 8, 22))
user8 = User.create!(firstname: "shark", lastname: "yung", password: "shark123", email: "shark@gmail.com", zipcode: "94928", birthday: Date.new(1984, 9, 27))
user9 = User.create!(firstname: "angela", lastname: "hemon", password: "angela123", email: "angela@gmail.com", zipcode: "92458", birthday: Date.new(1985, 10, 2))
user10 = User.create!(firstname: "ryan", lastname: "tran", password: "ryan123", email: "ryan@gmail.com", zipcode: "98938", birthday: Date.new(1887, 1, 8))
user11 = User.create!(firstname: "fonsi23", lastname: "nomura", password: "fonsi23123", email: "fonsi23@gmail.com", zipcode: "92328", birthday: Date.new(2000, 2, 3))

biz_data = [
  {
    "business_name" => "Fog Harbor Fish House",
    "url" => "https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.809041,
    "longitude" => -122.410233,
    "phone" => "+14154212442",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "Pier 39",
    "address2" => "Ste A-202",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "The House",
    "url" => "https://www.yelp.com/biz/the-house-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.79851,
    "longitude" => -122.40706,
    "phone" => "+14159868612",
    "price" => "$$$",
    "rating" => 4.5,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1230 Grant Ave",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Liholiho Yacht Club",
    "url" => "https://www.yelp.com/biz/liholiho-yacht-club-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.78818,
    "longitude" => -122.41458,
    "phone" => "+14154405446",
    "price" => "$$$",
    "rating" => 4.5,
    "zipcode" => "94109",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "871 Sutter St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Farmhouse Kitchen Thai Cuisine",
    "url" => "https://www.yelp.com/biz/farmhouse-kitchen-thai-cuisine-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.76026094,
    "longitude" => -122.4112048,
    "phone" => "+14158142920",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94110",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "710 Florida St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "The Front Porch",
    "url" => "https://www.yelp.com/biz/the-front-porch-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7438,
    "longitude" => -122.422035,
    "phone" => "+14156957800",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94110",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "65 29th St",
    "address2" => "Ste A",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Tuba Authentic Turkish Restaurant",
    "url" => "https://www.yelp.com/biz/tuba-authentic-turkish-restaurant-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.754898,
    "longitude" => -122.422906,
    "phone" => "+14158268822",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94110",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1007 Guerrero St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "MaMo",
    "url" => "https://www.yelp.com/biz/mamo-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.80384,
    "longitude" => -122.43366,
    "phone" => "+14156587150",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94123",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "3659 Buchanan St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "The Cheesecake Factory",
    "url" => "https://www.yelp.com/biz/the-cheesecake-factory-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7872658401153,
    "longitude" => -122.407448,
    "phone" => "+14153914444",
    "price" => "$$",
    "rating" => 3.0,
    "zipcode" => "94102",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "251 Geary St",
    "address2" => "",
    "address3" => "Union Square",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Son & Garden",
    "url" => "https://www.yelp.com/biz/son-and-garden-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.783387,
    "longitude" => -122.419016,
    "phone" => "+14159137404",
    "price" => "",
    "rating" => 4.5,
    "zipcode" => "94109",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "700 Polk St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Limón Rotisserie",
    "url" => "https://www.yelp.com/biz/lim%C3%B3n-rotisserie-san-francisco-3?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7570514,
    "longitude" => -122.416461,
    "phone" => "+14158212134",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94110",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1001 S Van Ness Ave",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Zazie",
    "url" => "https://www.yelp.com/biz/zazie-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.765244,
    "longitude" => -122.4501138,
    "phone" => "+14155645332",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94117",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "941 Cole St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Marufuku Ramen SF",
    "url" => "https://www.yelp.com/biz/marufuku-ramen-sf-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.785155,
    "longitude" => -122.432075,
    "phone" => "+14158729786",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94115",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1581 Webster St",
    "address2" => "Ste 235",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Kokkari Estiatorio",
    "url" => "https://www.yelp.com/biz/kokkari-estiatorio-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.796996,
    "longitude" => -122.399661,
    "phone" => "+14159810983",
    "price" => "$$$",
    "rating" => 4.5,
    "zipcode" => "94111",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "200 Jackson St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "The Pawn Shop",
    "url" => "https://www.yelp.com/biz/the-pawn-shop-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.78106,
    "longitude" => -122.40834,
    "phone" => "+14158748041",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94103",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "993 Mission St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Gary Danko",
    "url" => "https://www.yelp.com/biz/gary-danko-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.80587,
    "longitude" => -122.42058,
    "phone" => "+14157492060",
    "price" => "$$$$",
    "rating" => 4.5,
    "zipcode" => "94109",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "800 N Point St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "um.ma",
    "url" => "https://www.yelp.com/biz/um-ma-san-francisco-3?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7655,
    "longitude" => -122.46608,
    "phone" => "+14155665777",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94122",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1220 9th Ave",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Loló",
    "url" => "https://www.yelp.com/biz/lol%C3%B3-san-francisco-4?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7573462,
    "longitude" => -122.4214034,
    "phone" => "+14156435656",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94110",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "974 Valencia St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Kitchen Story",
    "url" => "https://www.yelp.com/biz/kitchen-story-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7642352,
    "longitude" => -122.4306936,
    "phone" => "+14155254905",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94114",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "3499 16th St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Mona Lisa Restaurant",
    "url" => "https://www.yelp.com/biz/mona-lisa-restaurant-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.798371,
    "longitude" => -122.407778,
    "phone" => "+14159894917",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "353 Columbus Ave",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Pier Market Seafood Restaurant",
    "url" => "https://www.yelp.com/biz/pier-market-seafood-restaurant-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.8099386456994,
    "longitude" => -122.410550415516,
    "phone" => "+14159897437",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "Pier 39",
    "address2" => "Ste 103",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Skool",
    "url" => "https://www.yelp.com/biz/skool-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7685096967036,
    "longitude" => -122.402136325836,
    "phone" => "+14152558800",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94103",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1725 Alameda St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "The Dorian",
    "url" => "https://www.yelp.com/biz/the-dorian-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.80065,
    "longitude" => -122.4365,
    "phone" => "+14158142671",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94123",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "2001 Chestnut St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Scoma's Restaurant",
    "url" => "https://www.yelp.com/biz/scomas-restaurant-san-francisco-3?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.808952,
    "longitude" => -122.418487,
    "phone" => "+14157714383",
    "price" => "$$$",
    "rating" => 4.0,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1965 Al Scoma Way",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Sotto Mare Oysteria & Seafood",
    "url" => "https://www.yelp.com/biz/sotto-mare-oysteria-and-seafood-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.79979,
    "longitude" => -122.40834,
    "phone" => "+14153983181",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "552 Green St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Nopa",
    "url" => "https://www.yelp.com/biz/nopa-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.77483,
    "longitude" => -122.43746,
    "phone" => "+14158648643",
    "price" => "$$$",
    "rating" => 4.0,
    "zipcode" => "94117",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "560 Divisadero St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Noosh",
    "url" => "https://www.yelp.com/biz/noosh-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7880771447147,
    "longitude" => -122.43393894285,
    "phone" => "+14152315985",
    "price" => "$$",
    "rating" => 3.5,
    "zipcode" => "94115",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "2001 Fillmore St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Thanh Long",
    "url" => "https://www.yelp.com/biz/thanh-long-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.76017,
    "longitude" => -122.50609,
    "phone" => "+14156651146",
    "price" => "$$$",
    "rating" => 4.0,
    "zipcode" => "94122",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "4101 Judah St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Lark",
    "url" => "https://www.yelp.com/biz/lark-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.761243,
    "longitude" => -122.434248,
    "phone" => "+14154004623",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94114",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "4068 18th St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "House Of Prime Rib",
    "url" => "https://www.yelp.com/biz/house-of-prime-rib-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.79338,
    "longitude" => -122.4225,
    "phone" => "+14158854605",
    "price" => "$$$",
    "rating" => 4.0,
    "zipcode" => "94109",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1906 Van Ness Ave",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Izakaya KOU",
    "url" => "https://www.yelp.com/biz/izakaya-kou-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.784139,
    "longitude" => -122.432649,
    "phone" => "+14154419294",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94115",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1560 Fillmore St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Palm House",
    "url" => "https://www.yelp.com/biz/palm-house-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.797772,
    "longitude" => -122.432887,
    "phone" => "+14154004355",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94123",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "2032 Union St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Fondue Cowboy",
    "url" => "https://www.yelp.com/biz/fondue-cowboy-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7776832580566,
    "longitude" => -122.407096862793,
    "phone" => "+14154315100",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94103",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1052 Folsom St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Cockscomb",
    "url" => "https://www.yelp.com/biz/cockscomb-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.77865,
    "longitude" => -122.39733,
    "phone" => "+14159740700",
    "price" => "$$$",
    "rating" => 4.0,
    "zipcode" => "94107",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "564 4th St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Marrakech Magic Theater",
    "url" => "https://www.yelp.com/biz/marrakech-magic-theater-san-francisco-5?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.785843,
    "longitude" => -122.411816,
    "phone" => "+14157946893",
    "price" => "$$",
    "rating" => 5.0,
    "zipcode" => "94102",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "419 O'Farrell St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Capo's by Tony Gemignani",
    "url" => "https://www.yelp.com/biz/capos-by-tony-gemignani-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7985156,
    "longitude" => -122.4084149,
    "phone" => "+14159868998",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94133",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "641 Vallejo St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Troya",
    "url" => "https://www.yelp.com/biz/troya-san-francisco-3?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7893743915288,
    "longitude" => -122.434076070785,
    "phone" => "+14155631000",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94115",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "2125 Fillmore St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "San Tung",
    "url" => "https://www.yelp.com/biz/san-tung-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.763693,
    "longitude" => -122.469008,
    "phone" => "+14152420828",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94122",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1031 Irving St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Mandalay",
    "url" => "https://www.yelp.com/biz/mandalay-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7851484,
    "longitude" => -122.4643918,
    "phone" => "+14153863896",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94118",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "4348 California St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Serpentine",
    "url" => "https://www.yelp.com/biz/serpentine-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.758100271937,
    "longitude" => -122.38818876502,
    "phone" => "+14152522000",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94107",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "2495 3rd St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Barrel Head Brewhouse",
    "url" => "https://www.yelp.com/biz/barrel-head-brewhouse-san-francisco-5?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7757521780078,
    "longitude" => -122.446032238623,
    "phone" => "+14154166989",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94117",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1785 Fulton St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Fenikkusu",
    "url" => "https://www.yelp.com/biz/fenikkusu-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.754826,
    "longitude" => -122.422957,
    "phone" => "+14159238600",
    "price" => "",
    "rating" => 5.0,
    "zipcode" => "94110",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1009 Guerrero St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Marlowe",
    "url" => "https://www.yelp.com/biz/marlowe-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7783200510611,
    "longitude" => -122.396771288052,
    "phone" => "+14157771413",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94107",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "500 Brannan St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Coqueta",
    "url" => "https://www.yelp.com/biz/coqueta-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7984671979957,
    "longitude" => -122.396616339684,
    "phone" => "+14157048866",
    "price" => "$$$",
    "rating" => 4.0,
    "zipcode" => "94105",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "The Embarcadero",
    "address2" => "",
    "address3" => "Pier 5",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "QingShu",
    "url" => "https://www.yelp.com/biz/qingshu-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.76427,
    "longitude" => -122.46669,
    "phone" => "+14157026255",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94122",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "816 Irving St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Hog Island Oyster Co",
    "url" => "https://www.yelp.com/biz/hog-island-oyster-co-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.795831,
    "longitude" => -122.393303,
    "phone" => "+14153917117",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94111",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1 Ferry Bldg",
    "address2" => "",
    "address3" => "Shop 11",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Dokkaebier",
    "url" => "https://www.yelp.com/biz/dokkaebier-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.792865,
    "longitude" => -122.421444,
    "phone" => "+14156253203",
    "price" => "",
    "rating" => 5.0,
    "zipcode" => "94109",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1735 Polk St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Starbelly",
    "url" => "https://www.yelp.com/biz/starbelly-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.7640744,
    "longitude" => -122.4325634,
    "phone" => "+14152527500",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94114",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "3583 16th St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Osteria Bella",
    "url" => "https://www.yelp.com/biz/osteria-bella-san-francisco-2?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.78148,
    "longitude" => -122.46085,
    "phone" => "+14152210305",
    "price" => "$$",
    "rating" => 4.5,
    "zipcode" => "94118",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "3848 Geary Blvd",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Pa'ina Lounge & Restaurant",
    "url" => "https://www.yelp.com/biz/paina-lounge-and-restaurant-san-francisco?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.785115,
    "longitude" => -122.432376,
    "phone" => "+14158292642",
    "price" => "$$",
    "rating" => 4.0,
    "zipcode" => "94115",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "1865 Post St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  },
  {
    "business_name" => "Cafe De Casa",
    "url" => "https://www.yelp.com/biz/cafe-de-casa-san-francisco-4?adjust_creative=zgBK-vCCnsGThf8hf5z3iA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=zgBK-vCCnsGThf8hf5z3iA",
    "latitude" => 37.76236,
    "longitude" => -122.43471,
    "phone" => "",
    "price" => "",
    "rating" => 5.0,
    "zipcode" => "94114",
    "country" => "US",
    "state" => "CA",
    "city" => "San Francisco",
    "address1" => "3985 17th St",
    "address2" => "",
    "address3" => "",
    "is_claimed" => true,
    "is_closed" => false
  }
]

biz_data.each do |biz| 
    Business.create!(biz)
end